@port = 3001

### findAll
# @name findAll
GET http://localhost:{{port}}/api/order
 


### findALL populado
# @name findAllPopulated
GET http://localhost:{{port}}/api/order/populate



## ID
@id = {{createorder.response.body.data.id}}   
@idfirst ={{findAll.response.body.data[0].id}}


 
### GET ONE
GET http://localhost:{{port}}/api/order/{{idfirst}}

### GET BY OWNER CUIT NOT PAY ORDERS
@cuit = 23224249969
GET http://localhost:{{port}}/api/order/notPayOrdersByOwnerCuit/{{cuit}}

###GET BY SHOP ID
@shopId = 65c090e1ad3fb943fc5cb298
GET http://localhost:{{port}}/api/order/notPayOrdersByShop/{{shopId}}

### POST
# @name createorder
POST http://localhost:{{port}}/api/order
Content-Type: application/json

{
        
        "nameStrategy": "Te vamos a borrar",
        "obs": "   ",
        "showName": "Siempre Al Dia",
        "contract": "67b905fb4bd0c3f4c7685797",
        "spot": "654e3fbc97ea9f854e9fa08b",
        "regular": true,
        "regStructure": {
                "monday": ["25", "26", "27", "28"],
                "tuesday": ["5", "6", "7", "8"],
                "wednesday": ["9", "10", "11", "12"],
                "thursday": ["13", "14", "15", "16"],
                "friday": ["17", "18", "19", "20"],
                "saturday": ["21", "22", "23", "24"],
                "sunday": ["25", "26", "27", "28"]}
}


### POST NO REGULAR
# @name createorder
POST http://localhost:{{port}}/api/order
Content-Type: application/json


{
        "nameStrategy": "Deberia ser sin dias con precio de 0 y dar error",
        "obs": "    ",
        "showName": "Siempre Al Dia",
        "contract": "67b905fb4bd0c3f4c7685797",
        "spot": "654e3fbc97ea9f854e9fa08b",
        "regular": false,
        "notRegStructure": [["2025-2-25",["1", "2", "3", "4"]],["2025-2-26", ["5", "6", "7", "8"]],["2025-2-27",  ["9", "10", "11", "12"]], ["2025-2-28",  ["9", "10", "11", "12"]],  ["2025-2-27",  ["20", "19", "16", "12"]]]
}


### POST RENOVATE ORDERS
# @name renovarOrdenes
POST http://localhost:{{port}}/api/order/renovateOrders



### PUT Modifica todo el objeto -idempotente-
PUT http://localhost:{{port}}/api/order/{{id}}
Content-Type: application/json

{
       "nameStrategy": "ss",
        "obs": "s",
        "showName": "s",
        "month": "03-2000",
        "contract": "654aefd5c3991db6152",
        "spot": "654e3fbc97ea9f854e9fa08b"

}


### PATCH cancelar Orden
@id_cancel = 67bf76c35247889a06e58edc

PATCH http://localhost:{{port}}/api/order/cancelOrder/{{id_cancel}}
Content-Type: application/json

{
        //"id": "...."  , si la paso en la ruta no hace falta aca...
        "cancelDate": "2025-2-26"  ,
        "obs":     " Tendria que quedar paga"
}



### PATCH pagar una orden 
@id_pay = 67b933b14c4699fba61c5bf6
PATCH http://localhost:{{port}}/api/order/registerPayment/{{id_pay}}
Content-Type: application/json

{
        "paymentDate":"2025-2-26",
        "paymentForm":"Efectivo",
        "paymentObs":"Seguimos con problemas de horas"
}



### PATCH Modoficar spot
@id_order = 67bd36ac86f3a452435c8038

PATCH http://localhost:{{port}}/api/order/updateSpot/{{id_order}}
Content-Type: application/json

{
        "spot": "67bf732818c68fb2db06b5f4"
}

### PATCH Modifica parte del objeto -no idempotente-
PATCH http://localhost:{{port}}/api/order/{{id}}
Content-Type: application/json

{
        
       
        "month": "13-2023"
        
}


###DELETE
@idDelete=67c1fd8cfb69e379456a799b
DELETE http://localhost:{{port}}/api/order/{{idDelete}}

##DUDA me esta diciendo que lo borro cuando realmente no existe el ordero.