### findAll
# @name findAll
GET http://localhost:3001/api/price  

## ID
@id = {{createprice.response.body.data.id}}
@block= {{findAll.response.body.data[0].block.id}}
 
### GET ONE
GET http://localhost:3001/api/price/{{id}}

### POST
# @name createprice
POST http://localhost:3001/api/price
Content-Type: application/json

{
    "value": 100.00,
    "block": "{{block}}"
}


###POST A PRICE TO ALL BLOCKS
POST http://localhost:3001/api/price/all/
Content-Type: application/json

{
    "value": 3000
}





### PUTH Modifica todo el objeto -idempotente-
PUT http://localhost:3001/api/price/{{id}}
Content-Type: application/json

{
     "value": 200.00,
     "block":   "{{block}}"
}






###DELETE
DELETE http://localhost:3001/api/price/{{id}}

##DUDA me esta diciendo que lo borro cuando realmente no existe el priceo.