### GET ALL
# @name allShops
GET http://localhost:3001/api/shop
 
 
### ID
@idFirst={{allShops.response.body.data[0].id}}
@idOwner={{allShops.response.body.data[0].owner.id}}
@cuitOwner={{allShops.response.body.data[0].owner.cuit}}
@fantasyName={{allShops.response.body.data[0].fantasyName}}
@idContact={{allShops.response.body.data[0].contact.id}}
@id={{createShop.response.body.data.id}}



###GET ONE by id 
GET http://localhost:3001/api/shop/{{idFirst}}

### get shop by cuit and fantasyName
GET http://localhost:3001/api/shop/search?fantasyName={{fantasyName}}&cuit={{cuitOwner}}


### get shops by cuit
GET http://localhost:3001/api/shop/{{cuitOwner}}


###GET BY OWNER ID
GET http://localhost:3001/api/shop/owner/{{idOwner}}



### POST
# @name createShop
POST http://localhost:3001/api/shop
Content-Type: application/json

{
    "fantasyName": "Librería Normita 8",
    "address": "Belgrano 67",
    "billingType": "Responsable Inscripto",
    "mail": "normita@gmail.com",
    "usualPaymentForm": "Efectivo",
    "type": "Otro",
    "contact":"{{idContact}}",
    "owner": "{{idOwner}}"   
}

### PUT
PUT http://localhost:3001/api/shop/{{id}}
Content-Type: application/json 

{
    "fantasyName": "Transporte DJJB",
    "address": "12 de Abril 0596",
    "billingType": "Otro",
    "mail": "normitag@mail.com", 
    "usualPaymentForm": "Efectivo",
    "type": "PyME"
}


###Patch
PATCH  http://localhost:3001/api/shop/{{id}}
Content-Type: application/json 

{
  
    "address": "12 de Abril 0596",
    "billingType": "Consumidor Final",
    "mail": "djjb@gmail.com",
    "usualPaymentForm": "Efectivo",
    "type": "PyME"
}



### DELETE
DELETE http://localhost:3001/api/shop/{{id}}



