@port = 3001
### findAll
# @name findAll
GET http://localhost:{{port}}/api/contact

## ID
@id = {{createContact.response.body.data.id}}
@idFirst = {{findAll.response.body.data[0].id}}
@dniFirst = {{findAll.response.body.data[0].dni}}
 
### GET ONE
GET http://localhost:{{port}}/api/contact/{{idFirst}}

### CREATE
# @name createContact
POST http://localhost:{{port}}/api/contact
Content-Type: application/json

{
    "dni": "44393593",
    "name": "Belén",
    "lastname": "Paez",
    "contacts": ["3402583942", "lautarobrancatti@gmail.com"]

}

### PUTH Modifica todo el objeto -idempotente-
PUT http://localhost:{{port}}/api/contact/{{id}}
Content-Type: application/json

{
    "dni": "52572142",
    "name": "Vicky",
    "lastname": "Pei",
    "contacts": ["3402428992"]
}

### PATCH
PATCH http://localhost:{{port}}/api/contact/654ad0d341b4fa27919f8af8
Content-Type: application/json

{
    "dni": "12345679"
}

### DELETE

DELETE http://localhost:{{port}}/api/contact/{{id}}


### get contact by dni
GET http://localhost:{{port}}/api/contact/dni/44684239
Content-Type: application/json