### findAll
GET http://localhost:3001/api/owner

## ID
@id = {{createOwner.response.body.data.id}}

### GET ONE
GET http://localhost:3001/api/owner/{{id}}

### POST
# @name createOwner
POST http://localhost:3001/api/owner
Content-Type: application/json

{
    "cuit": "33333333333",
    "businessName": "Joaquín Lares",
    "fiscalCondition": "Otro" 
}

### PUTH Modifica todo el objeto -idempotente-
PUT http://localhost:3001/api/owner/654ada122beba8847bd81fa9
Content-Type: application/json

{
    "cuit": "23224249969",
    "businessName": "Transporte DJJB" ,
    "fiscalCondition": "Consumidor Final" 
}



### POST
# @name createOwnerToDelete
POST http://localhost:3001/api/owner
Content-Type: application/json

{
    "cuit": "1111111111",
    "businessName": "Transporte DJJB", 
    "fiscalCondition": "Consumidor Final" 
}


###DELETE 
@idtoDelete = 654ada5d2beba8847bd81faa
#{{createOwnerToDelete.response.body.data.id}}

DELETE http://localhost:3001/api/owner/{{idtoDelete}}

##DUDA me esta diciendo que lo borro cuando realmente no existe el contacto.

### get owner by cuit
GET http://localhost:3001/api/owner/cuit/12333333333
Content-Type: application/json
