### RUTAS DICEN BLOCKS en lugar de BLOCK

### get all blocks
# @name allBlocks
GET http://localhost:3001/api/block

@id ={{allBlocks.response.body.data[0].id}}    
### Get one block
GET http://localhost:3001/api/block/{{id}}


### Creater a block
POST http://localhost:3001/api/block
Content-Type: application/json
{
  "numBlock": "30",
  "startTime": "12:30:00"
}

### Creater all blocks
POST http://localhost:3001/api/block/all
Content-Type: application/json

{
 
}

### modificar un block(PUT - recurso completo e idempotente)
PUT http://localhost:3001/api/block/{{id}}
{
    "numBlock": "99",
    "startTime": "16:10:00"
}


### modificar un block (PATCH - recurso parcial)
PATCH http://localhost:3000/api/block/{{id}}
Content-Type: application/json

{
  "startTime": "23:30:00"
}


### borrar un block
DELETE http://localhost:3001/api/block/{{id}}



###BORRAR TODOS LOS BLOQUES 
DELETE http://localhost:3001/api/block/deleteall/