### RUTAS DICEN BLOCKS en lugar de BLOCK

### obtener todos los block
GET http://localhost:3001/api/block

    
### obtener un block
GET http://localhost:3001/api/block/654ea00bb050bda4bf4b6876

### CREAR TODOS LOS BLOQUES
POST http://localhost:3001/api/block/all
Content-Type: application/json

{
  "startTime": "12:30:00",
   "number": 30
}

### modificar un block(PUT - recurso completo e idempotente)
PUT http://localhost:3001/api/block/654ea00bb050bda4bf4b6885

{
    "numBlock": "99",
    "startTime": "16:10:00"
}



@id = 654cf9fe2a21a1f7dc60abc3
### modificar un block (PATCH - recurso parcial)
PATCH http://localhost:3000/api/block/{{id}}
Content-Type: application/json

{
  "startTime": "23:30:00"
}


### borrar un block
DELETE http://localhost:3001/api/block/{{id}}



###BORRAR TODOS LOS BLOQUES 
DELETE http://localhost:3001/api/block/deleteall/