### obtener todos los blocks 
GET http://localhost:3000/api/blocks


### obtener un block
GET http://localhost:3000/api/blocks/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo block
POST http://localhost:3000/api/blocks
Content-Type: application/json

{
  "startTime": "12:30:00",
  "number": 30
}

### modificar un block(PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/blocks/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "startTime": "04:30:00",
  "number": 40  
}

### modificar un block (PATCH - recurso parcial)
PATCH http://localhost:3000/api/blocks/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "startTime": "23:30:00", 
}

### borrar un block
DELETE http://localhost:3000/api/blocks/a02b91bc-3769-4221-beb1-d7a3aeba7dad