### findAll
# @name findAll
GET http://localhost:3001/api/spot

## ID
@idFirsth = {{findAll.response.body.data.0.id}} 
@id = {{createspot.response.body.data.id}}
 
### GET ONE
GET http://localhost:3001/api/spot/{{idFirsth}}

### POST
# @name createspot
POST http://localhost:3001/api/spot
Content-Type: application/json

{
    "name": "borarr",
    "long": 1

}

### PUTH Modifica todo el objeto -idempotente-
PUT http://localhost:3001/api/spot/{{id}}
Content-Type: application/json

{
    "name": "Audio",
    "long": 3

}
### PATCH Modifica solo los campos que se le pasan -no idempotente-
PATCH http://localhost:3001/api/spot/{{id}}
Content-Type: application/json

{

    "long": 4

}



###DELETE
DELETE http://localhost:3001/api/spot/{{id}}
